version: '3'
services:
  meetup-node:
    image: meetup/node
    restart: always
    build:
      context: ../
      dockerfile: prod/Dockerfile
    ports:
     - 3000:3000
    environment:
     - PORT=3000